version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cbacespace-app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/mycbacespace
    volumes:
      - ./src:/var/www/mycbacespace
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mycbacespace

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/mycbacespace
      - ./nginx/conf.d:/etc/nginx/conf.d

    networks:
      - mycbacespace

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mycbacespace
      MYSQL_USER: mycbacespace
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mycbacespace

networks:
  mycbacespace:

volumes:
  dbdata:
