name: Deploy to Production

on:
  push:
    branches:
      - main # Remplacez par le nom de votre branche de production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Mettez à jour vers la dernière version disponible

    - name: Setup Node.js
      run: |
        sudo apt-get update
        sudo apt-get install nodejs
        sudo apt-get install npm
        node --version
        npm --version

    - name: Install dependencies
      run: npm ci

    - name: Build Vite app
      run: npm run build


    - name: Deploy to production
      env:
        HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
        HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        HOST_PORT: ${{ secrets.HOST_PORT }}
      run: |
        scp -o StrictHostKeyChecking=no -p 65002 -r ./public/build/* u958181990@89.116.147.102:/home/u958181990/domains/cbace-cga.com/public_html/cga-app
