name: Deploy to Production

on:
  push:
    branches:
      - main # Remplacez par le nom de votre branche de production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Mettez à jour vers la dernière version disponible

    - name: Setup Node.js
      run: |
        sudo apt-get update
        sudo apt-get install nodejs npm sshpass
        node --version
        npm --version

    - name: Install dependencies
      run: npm ci

    - name: Build Vite app
      run: npm run build

    - name: Deploy to production
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        REMOTE_PATH: '/home/ubuntu/cbacecga-app' # Remplacez par le chemin de votre répertoire distant
      run: |
        sshpass -p "$VPS_PASSWORD" scp -o StrictHostKeyChecking=no -P 22 -r ./* $VPS_USER@$VPS_IP:$REMOTE_PATH
