name: Deploy to Production

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  
    
    - name: Setup Node.js
      uses: actions/setup-node@v2  
      with:
        node-version: '20' 
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Vite app
      run: npm run build

    - name: Test SSH connection
      env:
        HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
        HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        HOST_PORT: ${{ secrets.HOST_PORT }}  
      run: |
        ssh -o StrictHostKeyChecking=no -p $HOST_PORT $HOST_USERNAME@${{ secrets.HOST_ADDRESS }} 'echo "SSH connection successful"'

    - name: Deploy to production
      env:
        HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
        HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        HOST_PORT: ${{ secrets.HOST_PORT }}  
      run: |
        scp -P $HOST_PORT -r ./build/* $HOST_USERNAME@${{ secrets.HOST_ADDRESS }}:/home/u958181990/domains/cbace-cga.com/public_html/cga-app/build
