name: Deploy to Production

on:
  push:
    branches:
      - main # Remplacez par le nom de votre branche de production

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Ajustez la version de Node.js selon vos besoins
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Vite app
      run: npm run build
      
    - name: Deploy to production
      env:
        HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
        HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
      run: |
        scp -r ./public/build/* $HOST_USERNAME@${{ secrets.HOST_ADDRESS }}:/home/u958181990/domains/cbace-cga.com/public_html/cga-app